settings:
  language: en_US
  min-length: 3 # minimum number of characters excluding color
  max-length: 15 # maximum number of characters excluding color
  signature-limit: 10 # number of signatures per item
  direct-sign: false # directly sign an item you are holding | permission needed if false: signatures.sign.direct
  format: # -- edit this BEFORE you put into your production environment! You cannot remove previous signatures after editing. --
    header: "&7Signatures:"
    each: " &7- "

  # Rename this item using the same command </sign ...> and drag/drop onto an item
  # Acquire via /signature item [player]
  signature-item:
    material: NAME_TAG
    modelData: -1
    name: "&bYour Signature &8(&7/sign&8)"
    lore:
      - "&8Current:&f %signature%"

blacklist:
  - 'frick'

# recommend not to change
# will create a backup if a new config is needed
version: 1
