name: Signatures
version: ${project.version}
main: me.pineacle.signatures.SignaturesPlugin
api-version: 1.16
authors: [ pineacle ]
depend: [NBTAPI]
description: Personalize your item by allowing other players to add their signature.
commands:
  sign:
    aliases: signature
    description: Sign the item you are currently holding
  unsign:
    description: Removes a signature from an item
